"""add site_content and site_features tables

Revision ID: 219f74759916
Revises: 23ab7220bd34
Create Date: 2026-08-05 17:02:29.700014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219f74759916'
down_revision: Union[str, Sequence[str], None] = '23ab7220bd34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_badge', sa.String(length=255), nullable=True),
    sa.Column('hero_heading', sa.String(length=500), nullable=False),
    sa.Column('hero_subheading', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_content_id'), 'site_content', ['id'], unique=False)
    op.create_table('site_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_features_id'), 'site_features', ['id'], unique=False)
    # ### end Alembic commands ###

    site_content_table = sa.table(
        'site_content',
        sa.column('hero_badge', sa.String),
        sa.column('hero_heading', sa.String),
        sa.column('hero_subheading', sa.Text),
    )
    op.bulk_insert(site_content_table, [{
        'hero_badge': 'AI-driven eCommerce, built for speed',
        'hero_heading': 'Launch your online store in minutes.',
        'hero_subheading': (
            "AutoCommerce gives you a storefront, a catalog, a team, and the analytics to run "
            "them — all from one dashboard. No code required to get started."
        ),
    }])

    site_features_table = sa.table(
        'site_features',
        sa.column('icon', sa.String),
        sa.column('title', sa.String),
        sa.column('description', sa.String),
        sa.column('sort_order', sa.Integer),
    )
    op.bulk_insert(site_features_table, [
        {
            'icon': 'Store', 'sort_order': 0, 'title': 'Your own storefront',
            'description': "Launch on a free subdomain instantly, or connect a custom domain when you're ready.",
        },
        {
            'icon': 'Boxes', 'sort_order': 1, 'title': 'Products with real variants',
            'description': "Size, color, or any attribute you define — each variant tracks its own price and stock.",
        },
        {
            'icon': 'Users', 'sort_order': 2, 'title': 'Team roles that make sense',
            'description': "Invite staff with owner, manager, staff, or support roles — each with scoped permissions.",
        },
        {
            'icon': 'BarChart3', 'sort_order': 3, 'title': 'Analytics from day one',
            'description': "Revenue, orders, and customer counts on one dashboard — no spreadsheets required.",
        },
        {
            'icon': 'ShieldCheck', 'sort_order': 4, 'title': 'Secure by default',
            'description': "Rotating refresh tokens, hashed credentials, and per-store data isolation.",
        },
        {
            'icon': 'Globe', 'sort_order': 5, 'title': 'Built for scale',
            'description': "Multi-tenant architecture designed to host thousands of independent stores.",
        },
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_features_id'), table_name='site_features')
    op.drop_table('site_features')
    op.drop_index(op.f('ix_site_content_id'), table_name='site_content')
    op.drop_table('site_content')
    # ### end Alembic commands ###
