"""add plans and subscriptions

Revision ID: 3f7be24e3639
Revises: f1b706dba16d
Create Date: 2026-07-27 22:47:12.645271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7be24e3639'
down_revision: Union[str, Sequence[str], None] = 'f1b706dba16d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('max_products', sa.Integer(), nullable=True),
    sa.Column('max_staff', sa.Integer(), nullable=True),
    sa.Column('custom_domain_allowed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_slug'), 'plans', ['slug'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###

    plans_table = sa.table(
        'plans',
        sa.column('name', sa.String),
        sa.column('slug', sa.String),
        sa.column('price', sa.Numeric),
        sa.column('billing_cycle', sa.String),
        sa.column('max_products', sa.Integer),
        sa.column('max_staff', sa.Integer),
        sa.column('custom_domain_allowed', sa.Boolean),
    )
    op.bulk_insert(plans_table, [
        {
            'name': 'Free', 'slug': 'free', 'price': 0, 'billing_cycle': 'trial',
            'max_products': 20, 'max_staff': 3, 'custom_domain_allowed': False,
        },
        {
            'name': 'Basic', 'slug': 'basic', 'price': 999, 'billing_cycle': 'monthly',
            'max_products': 200, 'max_staff': 5, 'custom_domain_allowed': True,
        },
        {
            'name': 'Pro', 'slug': 'pro', 'price': 2499, 'billing_cycle': 'monthly',
            'max_products': None, 'max_staff': None, 'custom_domain_allowed': True,
        },
    ])

    # Grandfather existing stores (created before subscriptions existed) onto Pro
    # with no expiry, rather than dropping them into a 7-day trial retroactively.
    op.execute("""
        INSERT INTO subscriptions (store_id, plan_id, status, current_period_end)
        SELECT s.id, (SELECT id FROM plans WHERE slug = 'pro'), 'active', NULL
        FROM stores s
        WHERE NOT EXISTS (SELECT 1 FROM subscriptions sub WHERE sub.store_id = s.id)
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_plans_slug'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
