"""add guest checkout and shipping fields to orders

Revision ID: 54765800892c
Revises: 88f3a3f1f45c
Create Date: 2026-08-06 15:23:02.622334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54765800892c'
down_revision: Union[str, Sequence[str], None] = '88f3a3f1f45c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_method', sa.String(length=20), server_default='cod', nullable=False))
    op.add_column('orders', sa.Column('contact_name', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('contact_email', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('contact_phone', sa.String(length=30), nullable=False))
    op.add_column('orders', sa.Column('shipping_address', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('shipping_city', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('shipping_postal_code', sa.String(length=20), nullable=True))
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'shipping_postal_code')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'contact_phone')
    op.drop_column('orders', 'contact_email')
    op.drop_column('orders', 'contact_name')
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
