"""add order channel

Revision ID: 5a730e780390
Revises: ef82419f99f5
Create Date: 2026-08-07 01:13:54.588267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a730e780390'
down_revision: Union[str, Sequence[str], None] = 'ef82419f99f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('channel', sa.String(length=10), server_default='online', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'channel')
    # ### end Alembic commands ###
