"""add currency to stores

Revision ID: a28c5214113d
Revises: 8e76beeae4f1
Create Date: 2026-07-27 21:09:03.697152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28c5214113d'
down_revision: Union[str, Sequence[str], None] = '8e76beeae4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'currency')
    # ### end Alembic commands ###
