"""add store profile fields

Revision ID: f1b706dba16d
Revises: a28c5214113d
Create Date: 2026-07-27 22:08:16.055947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b706dba16d'
down_revision: Union[str, Sequence[str], None] = 'a28c5214113d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('tag_line', sa.String(length=255), nullable=True))
    op.add_column('stores', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('stores', sa.Column('phone_country_code', sa.String(length=5), nullable=True))
    op.add_column('stores', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('stores', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('stores', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('stores', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('stores', sa.Column('zip_code', sa.String(length=20), nullable=True))
    op.add_column('stores', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'address')
    op.drop_column('stores', 'zip_code')
    op.drop_column('stores', 'city')
    op.drop_column('stores', 'state')
    op.drop_column('stores', 'country')
    op.drop_column('stores', 'phone_number')
    op.drop_column('stores', 'phone_country_code')
    op.drop_column('stores', 'email')
    op.drop_column('stores', 'tag_line')
    # ### end Alembic commands ###
